spring:
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql

logging:
  level:
    com.jean.reactivecoroutinestudy: debug
    org:
      springframework:
        r2dbc: DEBUG
server:
  port: 8081
